// Generated by Wrangler on Wed Jun 19 2024 10:29:05 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	ACCOUNT_ID: "fa3e82d8258ac121c26085c2a5952780";
	SERVICE_NAME: "cloudflare-agentic-ai-browser";
	tail_consumers: [{"service":"cloudflare-agentic-ai-browser-tail"}];
	OPENAI_API_KEY: string;
	BROWSER: DurableObjectNamespace;
	BUCKET: R2Bucket;
	DB: D1Database;
	RATE_LIMITER: any;
	MYBROWSER: Fetcher;
	AI: Ai;
}
