// Generated by Wrangler on Mon Jun 17 2024 12:11:08 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	ACCOUNT_ID: "fa3e82d8258ac121c26085c2a5952780";
	SERVICE_NAME: "cloudflare-agentic-ai-browser";
	tail_consumers: [{"service":"cloudflare-agentic-ai-browser-tail"}];
	OPENAI_API_KEY: string;
	LANGCHAIN_API_KEY: string;
	BASELIME_API_KEY: string;
	BROWSER: DurableObjectNamespace;
	BUCKET: R2Bucket;
	MYBROWSER: Fetcher;
}
