// Generated by Wrangler on Sun Jun 16 2024 22:49:48 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	ACCOUNT_ID: "fa3e82d8258ac121c26085c2a5952780";
	OPENAI_API_KEY: string;
	BROWSER: DurableObjectNamespace;
	BUCKET: R2Bucket;
	MYBROWSER: Fetcher;
}
