#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-agentic-ai-browser"
main = "src/index.ts"
compatibility_date = "2024-06-14"
compatibility_flags = [ "nodejs_compat"]

browser = { binding = "MYBROWSER" }

# Bind an R2 Bucket
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "screenshots"
preview_bucket_name = "screenshots-test"

# Binding to a Durable Object
[[durable_objects.bindings]]
name = "BROWSER"
class_name = "Browser"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Browser"] # Array of new classes

[vars]
ACCOUNT_ID="fa3e82d8258ac121c26085c2a5952780"